def get_database_schema_context() -> str:
    schema_lines = [
        "### MODELO DIMENSIONAL STAR SCHEMA:",
        "Tabelas disponíveis no banco de dados:",
        "- **d_calendario**: data_id (INT), data (DATE), ano (INT), mes (INT), nome_mes (VARCHAR), mes_ano (VARCHAR), trimestre (VARCHAR), semestre (VARCHAR), dia_semana (VARCHAR), dia_util (BOOLEAN)",
        "- **d_produtos**: produto_id (INT), sku (VARCHAR), nome_produto (VARCHAR), categoria (VARCHAR), subcategoria (VARCHAR), preco_tabela (DECIMAL), custo_base (DECIMAL), margem_alvo_pct (DECIMAL), classe_abc (VARCHAR)",
        "- **d_vendedores**: vendedor_id (INT), nome_vendedor (VARCHAR), regional (VARCHAR), cargo (VARCHAR), data_admissao (DATE), email (VARCHAR), status (VARCHAR)",
        "- **d_clientes**: cliente_id (INT), razao_social (VARCHAR), segmento (VARCHAR), porte (VARCHAR), estado (VARCHAR), regiao (VARCHAR)",
        "- **d_canais**: canal_id (INT), nome_canal (VARCHAR), tipo_canal (VARCHAR)",
        "- **f_metas**: meta_id (INT), ano (INT), mes (INT), data_id (INT), vendedor_id (INT), regional (VARCHAR), canal_id (INT), meta_faturamento (DECIMAL), meta_pedidos (INT), meta_margem_pct (DECIMAL)",
        "- **f_vendas**: venda_id (BIGINT), numero_pedido (VARCHAR), data_id (INT), produto_id (INT), vendedor_id (INT), cliente_id (INT), canal_id (INT), quantidade (INT), preco_unitario_praticado (DECIMAL), valor_bruto (DECIMAL), valor_desconto (DECIMAL), valor_liquido (DECIMAL), custo_total (DECIMAL), margem_contribuicao_valor (DECIMAL), margem_contribuicao_pct (DECIMAL), status_pedido (VARCHAR)",
        "",
        "### REGRAS DE NEGÓCIO E RELACIONAMENTOS:",
        "1. `f_vendas` é a tabela fato principal com as transações comerciais.",
        "   - `data_id` relaciona com `d_calendario.data_id` (formato YYYYMMDD).",
        "   - `produto_id` relaciona com `d_produtos.produto_id`.",
        "   - `vendedor_id` relaciona com `d_vendedores.vendedor_id`.",
        "   - `cliente_id` relaciona com `d_clientes.cliente_id`.",
        "   - `canal_id` relaciona com `d_canais.canal_id`.",
        "2. Métricas monetárias:",
        "   - Receita líquida faturada: `SUM(valor_liquido)` onde `status_pedido = 'Faturado'`.",
        "   - Lucro bruto / Margem em R$: `SUM(margem_contribuicao_valor)`.",
        "   - Margem de Contribuição %: `ROUND((SUM(margem_contribuicao_valor) / SUM(valor_liquido)) * 100, 2)`.",
        "   - Ticket Médio: `ROUND(SUM(valor_liquido) / COUNT(DISTINCT numero_pedido), 2)`.",
        "3. Metas: tabela `f_metas` possui `meta_faturamento` por vendedor e mês.",
        "4. Produtos: `classe_abc` é 'A', 'B' ou 'C'.",
        "5. Vendedores: Beatriz Silveira (Sudeste), Carlos Eduardo Mendes (Sul), Mariana Albuquerque (Sudeste), Lucas Fontes (Nordeste), Fernanda Rocha (Centro-Oeste).",
    ]
    return "\n".join(schema_lines)
